use std::fmt::Error;

pub async fn walk_randomly_in_room() -> Result<(), Error>{
    Ok(())
}